name: Metrics-Master
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
      - uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.isocalendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          token: ${{ secrets.METRICS_TOKEN }}
      - uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.habits.charts.svg
          base: ""
          plugin_habits: yes
          plugin_habits_from: 200       # Use 200 events to compute habits
          plugin_habits_days: 14        # Keep only events from last 14 days
          plugin_habits_facts: no       # Display facts section
          plugin_habits_charts: yes     # Display charts section
          plugin_habits_trim: no        # Trim unused hours on daily chart
          config_timezone: Europe/Paris # Set timezone
          token: ${{ secrets.METRICS_TOKEN }}
      - uses: lowlighter/metrics@master
        with:
          base: ""
          filename: metrics.plugin.languages.details.svg
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, percentage
          token: ${{ secrets.METRICS_TOKEN }}
